# Generated by Django 4.2.4 on 2023-08-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='text',
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='название подписки'),
        ),
    ]
