# Generated by Django 4.2.4 on 2023-08-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_sub_name_subscription_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписка оформлена'),
        ),
    ]
