# Generated by Django 4.2.4 on 2023-08-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_lesson_video_url_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-course', '-lesson', '-amount', '-date', '-method'), 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
