# Generated by Django 4.2.4 on 2023-08-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='user',
            new_name='owner',
        ),
    ]
